name: Validate Pull Request

# Trigger on pull request, for things that warrants re-build
on:
  pull_request:
    branches:
      - master
    paths:
      - .github/**
      - files/**
      - Dockerfile

jobs:
  get_latest_version:
    uses: ./.github/workflows/get_nexus_version_latest.yml

  # Verify image build success
  build_image:
    runs-on: ubuntu-latest
    needs: get_latest_version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Enable multi-architecture support on build node
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build image (no push)
        env:
          NEXUS_VERSION: ${{needs.get_latest_version.outputs.nexus_version}}
        run: |
          docker buildx build \
            --build-arg "NEXUS_VERSION=${NEXUS_VERSION}" \
            --label org.opencontainers.image.revision="${{github.sha}}" \
            --label org.opencontainers.image.version="${NEXUS_VERSION}" \
            --platform "linux/arm/v7,linux/arm64" \
            --pull \
            --output "type=image,push=false" \
            --file ./Dockerfile .
